# Site settings
title: Yuanyuan Mao
description: 'Business Card Page'
url: 'https://ymao94.github.io/'
baseurl: ''
profilepic: '/images/Profil.jpg'
bkimage: '/images/cover.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Yuanyuan Mao'
  email: yybmao@gmail.com
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username: ymao94
  linkedin_username:  yybmao
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md']
#exclude: ['README.md', 'screenshot-overview.png']
